theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "net"
device = "wlp0s20f3"

[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "battery"
interval=10
format= "{percentage}% {power}W"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
